Repository cubed-dev/cubed, pull requests merged in 2023-07, with the labels that each got.

#245 Account for reserved_mem when creating arrays
  cubed/core/plan.py
  cubed/tests/test_mem_utilization.py
Labels: bug

#246 Use np.unravel_index rather than iterating over np.ndindex
  cubed/core/ops.py
  cubed/tests/runtime/test_lithops_retries.py
Labels: optimization

#250 Document strong consistency
  docs/user-guide/reliability.md
Labels: documentation

#251 Avoid divide by zero from projected mem
  cubed/core/plan.py
Labels: bug

#252 Scaling docs
  docs/user-guide/index.md
  docs/user-guide/scaling.md
Labels: documentation, scaling

#241 Dask delayed executor
  cubed/runtime/executors/dask.py
Labels: enhancement

#253 Remove PipelineExecutor classes
  cubed/core/plan.py
  cubed/runtime/executors/beam.py
  cubed/runtime/executors/lithops.py
  cubed/runtime/types.py
  cubed/tests/primitive/test_blockwise.py
  cubed/tests/primitive/test_rechunk.py
  cubed/tests/utils.py
  cubed/vendor/rechunker/executors/__init__.py
  cubed/vendor/rechunker/executors/python.py
Labels: runtime

#258 Add type hints for runtime
  cubed/runtime/backup.py
  cubed/runtime/executors/lithops.py
  cubed/runtime/executors/lithops_retries.py
  cubed/runtime/executors/modal.py
  cubed/runtime/executors/modal_async.py
  cubed/runtime/executors/python.py
  cubed/runtime/executors/python_async.py
  cubed/runtime/pipeline.py
  cubed/runtime/types.py
  cubed/runtime/utils.py
Labels: runtime

#260 Coiled Functions executor
  .coveragerc
  cubed/runtime/executors/coiled.py
  examples/coiled/aws/README.md
  examples/coiled/aws/coiled-add-asarray.py
  examples/coiled/aws/requirements.txt
  pyproject.toml
  setup.cfg
Labels: runtime
